version: "3"

services:
  queue:
    tty: true
    image: rabbitmq:latest
    ports:
      - "5672:5672"

  consumer:
    tty: true
    restart: always
    build: ./consumer
    links:
      - queue
      - database

  database:
    tty: true
    restart: always
    build: ./database
    ports:
      - "8080:5432"
